name: cmake

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.clang-format'
      - '.clangd'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'docs/**'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: Jimver/cuda-toolkit@v0.2.20
        id: cuda-toolkit
        with:
          cuda: '12.6.3'

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup msvc sysroot for cmake
        if: matrix.os == 'windows-2022'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Generate vcpkg.json
        continue-on-error: true
        env:
          VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
        run: |
          cmake --preset release

      - name: Setup vcpkg
        id: vcpkg
        uses: johnwason/vcpkg-action@v6
        with:
          manifest-dir: "${{ github.workspace }}/build"
          triplet: x64-windows-release
          cache-key: ${{ matrix.os }}
          revision: master
          token: ${{ github.token }}
          github-binarycache: true
          fetch-depth: '0'

      - name: Build libuipc
        env:
          VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
        run: |
          cmake --preset ci-release
          cmake --build --preset ci-release
