name: cmake

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.clang-format'
      - '.clangd'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'docs/**'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup cuda
        uses: Jimver/cuda-toolkit@v0.2.20
        id: cuda-toolkit
        with:
          cuda: '12.6.3'

      - name: Setup ninja & gcc14
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y gcc-14 g++-14 libstdc++-14-dev ninja-build
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
          sudo update-alternatives --set gcc /usr/bin/gcc-14
          sudo update-alternatives --set g++ /usr/bin/g++-14

      - name: Setup ninja
        if: matrix.os == 'windows-2022'
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup msvc sysroot for cmake
        if: matrix.os == 'windows-2022'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Generate vcpkg.json
        continue-on-error: true
        env:
          VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
        run: |
          cmake --preset release

      - name: Setup vcpkg
        id: vcpkg
        uses: johnwason/vcpkg-action@v6
        with:
          manifest-dir: "${{ github.workspace }}/build"
          triplet: ${{ matrix.os == 'windows-2022' && 'x64-windows-release' || 'x64-linux' }}
          cache-key: ${{ matrix.os }}
          revision: master
          token: ${{ github.token }}
          github-binarycache: true
          fetch-depth: '0'

      - name: Build libuipc
        env:
          VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
        run: |
          cmake --preset ci-release
          cmake --build --preset ci-release
